site_name: "csrs Documentation"
nav:
  - Home: index.md
  - API Reference: api.md
  - Tutorials: tutorials.md
theme: 
  name: "readthedocs"
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_root_toc_entry: false
            heading_level: 3
            members_order: source
