# This is the configuration file for the Scenario Manager Studies Repo

[[studies]]
name="Historical"
sv="C:/Users/zroy/Documents/_Modeling/_2023DCR/_studies/8.15.5_nile_hist/DSS/input/DCR2023_SV_Nile_Hist_v14.dss"
dv="C:/Users/zroy/Documents/_Modeling/_2023DCR/_studies/8.15.5_nile_hist/DSS/output/DCR2023_DV_8.15.5_Nile_Hist_v14.dss"

[[studies]]
name="Adjusted Historical"
sv="C:/Users/zroy/Documents/_Modeling/_2023DCR/_studies/8.15.5_nile_histadj/DSS/input/DCR2023_SV_Nile_Adj_v15.dss"
dv="C:/Users/zroy/Documents/_Modeling/_2023DCR/_studies/8.15.5_nile_histadj/DSS/output/DCR2023_DV_8.15.5_Nile_Adj_v15.dss"