{% set data = load_file_data('../pyproject.toml', from_recipe_dir=True) %}


package:
  name: csrs
  version: {{ data['project']['version'] }}

source:
  path: ..

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - pip
    - python=3.11
    - setuptools
  run:
    - python=3.11
    - fastapi
    - packaging
    - pandss>=0.7.3
    - uvicorn
    - sqlalchemy
    - jinja2
    - python-multipart
  
about:
  home: https://github.com/CentralValleyModeling/csrs