[[objects]]
scenario = "Historical"
version = "1.1"
dss = "//cnrastore-bdo/CVM_Inventory/_DeliveryCapabilityReport/2023_DCR_Studies/Modeling/draft/Second_Iteration_Runs_ICC_CCWD/9.0.0_danube_hist/DSS/output/DCR2023_DV_9.0.0_Danube_Hist_v1.1.dss"


[[objects]]
scenario = "Adjusted Historical"
version = "1.2"
dss = "//cnrastore-bdo/CVM_Inventory/_DeliveryCapabilityReport/2023_DCR_Studies/Modeling/draft/Second_Iteration_Runs_ICC_CCWD/9.0.0_danube_histadj/DSS/output/DCR2023_DV_9.0.0_Danube_Adj_v1.2.dss"


[[objects]]
scenario = "Climate Change Level of Concern 50%"
version = "1.2.1"
dss = "//cnrastore-bdo/CVM_Inventory/_DeliveryCapabilityReport/2023_DCR_Studies/Modeling/draft/Second_Iteration_Runs_ICC_CCWD/9.0.0_danube_cc50/DSS/output/DCR2023_DV_9.0.0_Danube_CC50_v1.2.1.dss"


[[objects]]
scenario = "Climate Change Level of Concern 75%"
version = "1.2.1"
dss = "//cnrastore-bdo/CVM_Inventory/_DeliveryCapabilityReport/2023_DCR_Studies/Modeling/draft/Second_Iteration_Runs_ICC_CCWD/9.0.0_danube_cc75/DSS/output/DCR2023_DV_9.0.0_Danube_CC75_v1.2.1.dss"


[[objects]]
scenario = "Climate Change Level of Concern 95%"
version = "1.2.1"
dss = "//cnrastore-bdo/CVM_Inventory/_DeliveryCapabilityReport/2023_DCR_Studies/Modeling/draft/Second_Iteration_Runs_ICC_CCWD/9.0.0_danube_cc95/DSS/output/DCR2023_DV_9.0.0_Danube_CC95_v1.2.1.dss"
